### ISSUE TITLE
As a user: I can ask or/and answer a question on the website

### ISSUE THREAD

**Issue by Bogdanpoda** [Bogdanpoda/SOEN341#31]
- [ ] User Story: 
Users can ask questions & answer questions asked by other users. 

- [ ] Story Points: 100 Points

- [ ] Acceptance test:
- website: The index page of the website is displaying a text box where the user can input a text question 
- Button "ask" that store the question into the server database when clicked
- checks if the user is logged in before asking the question
- when logged in each user should have a dedicated section where he/she can see its asked question
- for each question in the database, it is linked to the user who has asked it and to the answers for that question
- create a question component (object) that would contain the (question + answer + upvotes)

- [ ] Risk level: high
If users can not ask or answer questions then, the best answer feature will not work.
The main goal of this website is to ask questions.

- [ ] Priority: high
- priority number (1) most important core feature required for testing the others main core features 
- should be the first implemented feature

- [ ] User Story Tasks:
- Make a forum page for all the questions & answers
