### ISSUE TITLE
As a user I can upvote or downvote a question

### ISSUE THREAD

**Issue by siar2112** [Bogdanpoda/SOEN341#32]
- [ ] User Story: 
Create a button that the logged-in users can click on to increase the counter. Should be able to see the most Upvoted answer.

- [ ] Story Points: 100 Points

- [ ] Priority: medium
It's the second most important core feature. This allows the third feature to be functional as it allows to sort the questions and answer

- [ ] Risk level: medium
Linking of questions to Upvote/ Downvote can change the position of questions depending on the method of implementation.

- [ ] Acceptance test
- an upvote add up by one  the total score of a question and a downvote drop the total score by one 
- the total score of a question is shown on the web page
- Only login users can vote
- the backend is updated when a user vote

- [ ]  User Story Tasks 
- Linking of the question
- Create buttons 
- Create counters for buttons

**Comment by nadiaaab** [comment]
liking of the question, upvote downvote completed
