### ISSUE TITLE
User Story: Accepting the best answer

### ISSUE THREAD

**Issue by cemichaud** [Bogdanpoda/SOEN341#33]
- [ ] User Story: 
As a user of the website for programmers, I want to be able to see the highest-rated answer at the top of the page and the lowest-rated answers at the bottom of the page in order to view the most approved answer.

- [ ] Story Points: 100 Points

- [ ] Risk level: low
The user who asked the question chooses one answer to be the best answer.

- [ ] Priority: low

- [ ] Acceptance test : 
- Most approved answers are based on the user that asked the question
- Most approved answers found at the top of the page
- Sort in decreasing order the answers in terms of the number of upvotes
- Best answer can only be decided by the user who asked the question

- [ ] User Story Tasks:
- Linking of questions to the upvote/ downvote counters
- Upvote button
- Downvote button

**Comment by nadiaaab** [comment]
finished, best answer is properly accepted and displayed for the user to see

**Comment by cemichaud** [comment]
closed
