### ISSUE TITLE
Search questions functionality 

### ISSUE THREAD

**Issue by Pineapple920** [Bogdanpoda/SOEN341#47]
- [ ] User Story:
As a user of the website for programmers, all questions asked must be searchable

- [ ] Story Points: 100 Points

- [ ] Risk level: low
The user searching for questions interacting with the website environment

 - [ ] Priority: low
Ask a question core feature must work properly to allow for search feature to work

- [ ]  Acceptance test :

website: The index page of the website is displaying a text box where the user can input a text to the search

for each question in the database, it must be searchable through the text box

 - [ ] User Story Tasks:

Search bar for searching questions.

List of questions answered and unanswered.

**Comment by nadiaaab** [comment]
index page with text input to search completed, each question is searchable through the text box
